name: Update and deploy daily

on:
  schedule:
    - cron: "0 5 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT}}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          renv::restore(packages = c("curl", "data.table", "dplyr", "fable",
          "fabletools", "feasts", "glue", "htmltools", "janitor", "lubridate",
          "purrr", "tidyr", "tsibble", "usethis"))
        shell: Rscript {0}

      - name: Update data
        run: |
          source("R/utils_data_wrangle.R")
          source("R/utils_get_data.R")
          source("R/utils_module_dataviz.R")
          source("R/utils_module_overview_month.R")
          source("R/utils_module_overview_week.R")
          source("R/utils_module_overview_year.R")
          source("R/utils_module_predictions.R")
          source("R/utils_module_zh_details.R")
          load("data/zh_old.rda")
          load("data/wi_old.rda")
          load("data/bs_old.rda")
          source("data-raw/02_get_updated_data.R")
          source("data-raw/03_prepare_data_for_modules.R")
        shell: Rscript {0}

      # build the docker image and give it the name main
      - name: Build image
        run: docker build -t main .
      # run the docker image supply the secrets from the github secrets store.
      - name: execute
        run: >
          docker run
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }}
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -e APP_NAME=${{secrets.APP_NAME}}
          main
