name: Update last year's ddata
# workflow that runs on 1st january for new old data and commits it
on:
  schedule:
    - cron: "0 3 1 1 *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT}}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          install.packages(c("curl", "data.table", "dplyr", "fable",
          "fabletools", "feasts", "glue", "htmltools", "janitor", "lubridate",
          "purrr", "tidyr", "tsibble", "usethis"))
        shell: Rscript {0}

      - name: Update data
        run: |
          source("R/utils_data_wrangle.R")
          source("R/utils_get_data.R")
          source("R/utils_module_dataviz.R")
          source("R/utils_module_overview_month.R")
          source("R/utils_module_overview_week.R")
          source("R/utils_module_overview_year.R")
          source("R/utils_module_predictions.R")
          source("R/utils_module_zh_details.R")
          source("data-raw/01_get_data.R")
        shell: Rscript {0}

      # build the docker image and give it the name main
      -  name: Git Commit and Push Changes
         run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add last year's data to old data"
          git push
